--DROP TABLE IF EXISTS tb_students CASCADE; CREATE TABLE tb_students (
--  matricula BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
--  nome VARCHAR(150) NOT NULL,
--  cpf VARCHAR(11) NOT NULL
--);


